# this is a generated file, to avoid over-writing it just delete this comment
require 'jar_dependencies'

require_jar( 'io.netty', 'netty', '3.7.0.Final' )
require_jar( 'org.slf4j', 'slf4j-api', '1.6.1' )
require_jar( 'org.slf4j', 'slf4j-log4j12', '1.7.21' )
require_jar( 'org.scala-lang', 'scala-library', '2.11.8' )
require_jar( 'jline', 'jline', '0.9.94' )
require_jar( 'log4j', 'log4j', '1.2.15' )
require_jar( 'org.xerial.snappy', 'snappy-java', '1.1.2.4' )
require_jar( 'net.sf.jopt-simple', 'jopt-simple', '4.9' )
require_jar( 'org.apache.kafka', 'kafka-clients', '0.10.0.0' )
require_jar( 'junit', 'junit', '3.8.1' )
require_jar( 'javax.activation', 'activation', '1.1' )
require_jar( 'org.apache.kafka', 'kafka_2.11', '0.10.0.0' )
require_jar( 'com.yammer.metrics', 'metrics-core', '2.2.0' )
require_jar( 'org.apache.zookeeper', 'zookeeper', '3.4.6' )
require_jar( 'javax.mail', 'mail', '1.4' )
require_jar( 'com.101tec', 'zkclient', '0.8' )
require_jar( 'org.scala-lang.modules', 'scala-parser-combinators_2.11', '1.0.4' )
require_jar( 'net.jpountz.lz4', 'lz4', '1.3.0' )
